# Generated by Django 4.2.6 on 2023-10-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_category_item_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
