# Generated by Django 4.2.6 on 2023-11-08 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coupon_order_being_delivered_order_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='start_date',
            new_name='created_at',
        ),
    ]
