# Generated by Django 4.2.6 on 2023-11-08 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_start_date_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='start_date',
        ),
    ]
