# Generated by Django 4.2.6 on 2023-12-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
